version: '3.8'

services:
    api:
        container_name: api-dataprev
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            NODE_ENV: Development
        volumes:
            - .:/app
        ports:
            - '3000:3000'
        depends_on:
            - db
        command: ['npm', 'run', 'start:dev']

    db:
        container_name: postgres-dataprev
        image: postgres:15-alpine
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'

volumes:
    postgres_data:
